apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: maps-monitor
  name: maps-monitor
spec:
  endpoints:
    - interval: 30s
  port: http
  scheme: http
  selector:
    matchLabels:
      project: maps
